# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code. a
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  skipComponentGovernanceDetection: true
  system.debug: true

jobs:
  - job: abc
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - powershell: |
          gci env:*
      - powershell: |
          belh a
        displayName: 'Run a multi-line script'
        name: setStatus
      - powershell: |
          Write-Host $(Agent.JobStatus)
          Write-Host "##vso[task.setvariable variable=PrevJobStatus;isOutput=true]$(Agent.JobStatus)"
        condition: always()

  - job: def
    condition: always()
    dependsOn: abc
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      myVarFromJobA: $[ dependencies.abc.outputs['setStatus.PrevJobStatus'] ]
    steps:
      - powershell: |
          Write-Host $(Agent.JobStatus)
          Write-Host $(myVarFromJobA)
      
