# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
  - job: abc
    pool:
      vmImage: 'ubuntu-latest'

      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - powershell: |
          belh a
        displayName: 'Run a multi-line script'
  
  - job: def
    condition: always()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - powershell: |
          Write-Host $(Agent.JobStatus)
      